version: "3.9"
services:    
  nginx:
    build: ./nginx 
    links:
      - server-one
      - server-two
      - server-three
      - server-four
    ports:
    - "3000:80"

  server-one:
    build: ./cloudcomputing
    links:
      - redis
    expose:
      - "3000"
    environment:
      - NAME=one

  server-two:
    build: ./cloudcomputing
    links:
      - redis
    expose:
      - "3000"
    environment:
      - NAME=two

  server-three:
    build: ./cloudcomputing
    links:
      - redis
    expose:
      - "3000"
    environment:
      - NAME=three

  server-four:
    build: ./cloudcomputing
    links:
      - redis
    expose:
      - "3000"
    environment:
      - NAME=four
  
  mongo:
    image: mongo
    volumes:
      - ./userdata:/data/db
    ports:
      - "27017:27017"    

  redis:
    image: redis:alpine
    expose:
      - "6379"

volumes:
  userdata:
